# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-added-large-files
      - id: mixed-line-ending

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: cargo-check
      - id: clippy
        args: ["--all-targets", "--", "--deny", "warnings"]

  - repo: https://github.com/futuretech6/pre-commit-rust-nightly
    rev: v1.1
    hooks:
      - id: fmt
